IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'VIEW' AND TABLE_NAME = 'VIEW_LISTA_OS')
BEGIN
  EXECUTE(' CREATE VIEW VIEW_LISTA_OS AS  
	SELECT MI_ORDEM_SERVICO.DATAHORA as DATAHORA,        
	  MI_ORDEM_SERVICO.SOLICITANTE,        
	  MI_FUNCIONARIO.NOME as MANUTENTOR,        
	  isnull(MI_EQUIPAMENTO.DESCRICAO,''-'') AS DESC_DEFEITO,        
	  MI_ORDEM_SERVICO.CODIGO as OS,        
	  isnull(MI_OBJETO.TAG,''-'') as OBJETO,        
	  isnull(MI_OBJETO.DESCRICAO,'' - '') DESCRICAO_OBJETO,        
	  CASE WHEN MI_ORDEM_SERVICO.STATUS = ''1'' THEN ''Aguardando''         
	  when MI_ORDEM_SERVICO.STATUS =''4'' then ''Em atendimento''          
	   ELSE ''Finalizado'' END AS STATUS ,      
  
	   Case when (MI_FUNCIONARIO.NOME  is null) and (DATEDIFF(MINUTE, DATAHORA,getdate()) <= 3)  then ''Normal''   
			 when (MI_FUNCIONARIO.NOME  is null) and (DATEDIFF(MINUTE, DATAHORA,getdate()) > 3) and (DATEDIFF(MINUTE, DATAHORA,getdate()) <= 5) then ''Media''   
			 when (MI_FUNCIONARIO.NOME  is null) and (DATEDIFF(MINUTE, DATAHORA,getdate()) > 5) and (DATEDIFF(MINUTE, DATAHORA,getdate()) <= 10) then ''Alerta''   
			 when (MI_FUNCIONARIO.NOME  is null) and (DATEDIFF(MINUTE, DATAHORA,getdate()) > 10) then ''Critico''   
			 when MI_FUNCIONARIO.NOME  is not null then ''Okay'' end as SLA ,  
  
	   ''#FF0000'' as Cor       
	  FROM MI_ORDEM_SERVICO (NOLOCK)       
	 INNER JOIN MI_TIPO_MANUTENCAO ON MI_TIPO_MANUTENCAO.CODIGO = MI_ORDEM_SERVICO.TIPO_MANUTENCAO  
	   inner join MI_OBJETO ON MI_OBJETO.CODIGO = MI_ORDEM_SERVICO.OBJETO        
	   left JOIN MI_EQUIPAMENTO (NOLOCK) ON MI_EQUIPAMENTO.CODIGO = MI_ORDEM_SERVICO.CODIGO_EQUIPAMENTO  
	   LEFT JOIN FUNCIONARIOS(NOLOCK) ON FUNCIONARIOS.MATRIC = MI_ORDEM_SERVICO.SOLICITANTE        
	   left join MI_FUNCIONARIO (nolock) on MI_FUNCIONARIO.CODIGO = MI_ORDEM_SERVICO.CODIGO_FUNCIONARIO        
	WHERE MI_TIPO_MANUTENCAO.DESCRICAO = ''CORRETIVA EMERGENCIAL''  ')
END
go 


IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'VIEW' AND TABLE_NAME = 'VIEW_ORDENS_OBJETO')
BEGIN
	EXECUTE(' 
		CREATE VIEW VIEW_ORDENS_OBJETO AS    
		SELECT cast(ROW_NUMBER() over(order by DescObj ) as integer) as OS, DescObj, isnull(count(CodigoOS),0) as Total from (  
		select MI.CODIGO as CodigoOS, MI_OBJETO.CODIGO +'' - ''+ MI_OBJETO.DESCRICAO DescObj , mi.DATAHORA  as Abertura,      
			MI.SOLICITANTE as Soliticante, MI_FUNCIONARIO.NOME AS Manutentor,     
		   CASE WHEN MI.STATUS NOT IN (5,6) THEN ''Aberto''      
				when MI.STATUS  IN (5) THEN ''Fechado''      
				when MI.STATUS IN (6) THEN ''Cancelada'' end as Status              
			from MI_ORDEM_SERVICO MI                
		  INNER JOIN MI_TIPO_MANUTENCAO ON MI_TIPO_MANUTENCAO.CODIGO = MI.TIPO_MANUTENCAO  
		  INNER JOIN MI_OBJETO ON MI_OBJETO.CODIGO = MI.OBJETO  
		  LEFT JOIN MI_FUNCIONARIO ON MI_FUNCIONARIO.CODIGO = MI.CODIGO_FUNCIONARIO  
		where 1=1 and MI.STATUS IN (5)        
		 and MI_TIPO_MANUTENCAO.DESCRICAO = ''CORRETIVA EMERGENCIAL''       
		 AND FIM_REAL IS NOT NULL    
		-- and convert(varchar,DATAHORA,112) >= convert(varchar,getdate(),112)  
		) as tbl group by DescObj  
	')
END
go 

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'VIEW' AND TABLE_NAME = 'VIEW_ATENDIMENTO_TECNICO')
BEGIN
	EXECUTE(' CREATE VIEW VIEW_ATENDIMENTO_TECNICO AS    
				SELECT CAST(ROW_NUMBER() over(order by Manutentor ) AS INTEGER) as OS,  Manutentor, isnull(count(CodigoOS),0) as Total from (  
				select MI.CODIGO as CodigoOS, MI_OBJETO.CODIGO +'' - ''+ MI_OBJETO.DESCRICAO DescObj , mi.DATAHORA  as Abertura,      
					MI.SOLICITANTE as Soliticante, MI_FUNCIONARIO.NOME AS Manutentor,     
				   CASE WHEN MI.STATUS NOT IN (5,6) THEN ''Aberto''      
						when MI.STATUS  IN (5) THEN ''Fechado''      
						when MI.STATUS IN (6) THEN ''Cancelada'' end as Status              
					from MI_ORDEM_SERVICO MI                
				  INNER JOIN MI_TIPO_MANUTENCAO ON MI_TIPO_MANUTENCAO.CODIGO = MI.TIPO_MANUTENCAO  
				  INNER JOIN MI_OBJETO ON MI_OBJETO.CODIGO = MI.OBJETO  
				  LEFT JOIN MI_FUNCIONARIO ON MI_FUNCIONARIO.CODIGO = MI.CODIGO_FUNCIONARIO  
				where 1=1 and MI.STATUS IN (5)        
				 and MI_TIPO_MANUTENCAO.DESCRICAO = ''CORRETIVA EMERGENCIAL''       
				 AND FIM_REAL IS NOT NULL    
				-- and convert(varchar,DATAHORA,112) >= convert(varchar,getdate(),112)  
				 ) as tbl group by Manutentor   ')
END
go 

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'VIEW' AND TABLE_NAME = 'VIEW_MTBF_MES_A_MES')
BEGIN
	EXECUTE('  CREATE view VIEW_MTBF_MES_A_MES as  
			 SELECT CAST(ROW_NUMBER() over(order by TBL.Ano, TBL.Mes asc ) AS INTEGER) as OS, cast((( (ISNULL((DISP.TMP_DISPONIVEL * 60),0) - ISNULL(TBL.TEMPOTOTAL,0)) / ISNULL(TBL.N_OSES,0)) / 60) as decimal(19,2)) AS MTBF,  TBL.Mes, TBL.Ano FROM (  
			  SELECT COUNT(OS.CODIGO) AS N_OSES, SUm(TEMPOS.MINUTOS) AS TEMPOTOTAL, MONTH(OS.FIM_REAL) AS Mes,  YEAR(OS.FIM_REAL) AS Ano   
			  FROM MI_ORDEM_SERVICO OS (NOLOCK)  
				INNER JOIN (  
				 select RECNO_ORDEM_SERVICO,               
				  sum( DATEDIFF(MI,CAST( CONVERT(VARCHAR,DTHINICIAL,112) + '' '' + HORA_INI AS DATETIME),  CAST( CONVERT(VARCHAR,DTHFINAL,112) + '' '' + HORA_FIM AS DATETIME) ) ) AS MINUTOS               
					 from MI_APONTA_ORDEM_SERVICO (nolock)               
				 WHERE TIPO = ''Maquina''              
					 group by RECNO_ORDEM_SERVICO   
				) TEMPOS ON OS.R_E_C_N_O_ = TEMPOS.RECNO_ORDEM_SERVICO  
				WHERE OS.FIM_REAL BETWEEN EOMONTH(dateadd(month,-12,getdate()) +1) AND EOMONTH(getdate())  
			   GROUP BY MONTH(OS.FIM_REAL),  YEAR(OS.FIM_REAL)  
			  ) TBL INNER JOIN (  
				 SELECT SUM(DO.TEMPO_DISPONIVEL) AS TMP_DISPONIVEL, MES, ANO FROM  MI_DISPONIBILIDADE D  
				 INNER JOIN MI_DISPONIBILIDADE_OBJETO DO ON DO.RECNO_DISPONIBILIDADE = D.R_E_C_N_O_  
				 GROUP BY MES, ANO  
			  ) DISP ON DISP.ANO = TBL.Ano AND DISP.MES = TBL.Mes   
				WHERE 1=1     ')
END
go 

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'VIEW' AND TABLE_NAME = 'VIEW_MTTR_MES_A_MES')
BEGIN
	EXECUTE(' 
	 create view VIEW_MTTR_MES_A_MES as  
	 SELECT CAST(ROW_NUMBER() over(order by TBL.Ano, TBL.Mes asc ) AS INTEGER) as OS, cast((( ( ISNULL(TBL.TEMPOTOTAL,0)) / ISNULL(TBL.N_OSES,0)) / 60.00) as decimal(19,2)) AS MTTR,  TBL.Mes, TBL.Ano FROM (  
	  SELECT COUNT(OS.CODIGO) AS N_OSES, SUm(TEMPOS.MINUTOS) AS TEMPOTOTAL, MONTH(OS.FIM_REAL) AS Mes,  YEAR(OS.FIM_REAL) AS Ano   
	  FROM MI_ORDEM_SERVICO OS (NOLOCK)  
		INNER JOIN (  
		 select RECNO_ORDEM_SERVICO,               
		  sum( DATEDIFF(MI,CAST( CONVERT(VARCHAR,DTHINICIAL,112) + '' '' + HORA_INI AS DATETIME),  CAST( CONVERT(VARCHAR,DTHFINAL,112) + '' '' + HORA_FIM AS DATETIME) ) ) AS MINUTOS               
			 from MI_APONTA_ORDEM_SERVICO (nolock)               
		 WHERE TIPO = ''Maquina''              
			 group by RECNO_ORDEM_SERVICO   
		) TEMPOS ON OS.R_E_C_N_O_ = TEMPOS.RECNO_ORDEM_SERVICO  
		WHERE OS.FIM_REAL BETWEEN EOMONTH(dateadd(month,-12,getdate()) +1) AND EOMONTH(getdate())  
	   GROUP BY MONTH(OS.FIM_REAL),  YEAR(OS.FIM_REAL)  
	  ) TBL INNER JOIN (  
		 SELECT SUM(DO.TEMPO_DISPONIVEL) AS TMP_DISPONIVEL, MES, ANO FROM  MI_DISPONIBILIDADE D  
		 INNER JOIN MI_DISPONIBILIDADE_OBJETO DO ON DO.RECNO_DISPONIBILIDADE = D.R_E_C_N_O_  
		 GROUP BY MES, ANO  
	  ) DISP ON DISP.ANO = TBL.Ano AND DISP.MES = TBL.Mes   
		WHERE 1=1    
	')
END
go 


--criação usuário WEB com acesso a leitura.
USE [master]
CREATE LOGIN [dashboard] WITH PASSWORD=N'q1w2e3', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [MaintenanceDemo]
GO
CREATE USER [dashboard] FOR LOGIN [dashboard] WITH DEFAULT_SCHEMA=[dbo]
GO


grant select on [VIEW_LISTA_OS] to [dashboard] 
go

grant select on VIEW_ORDENS_OBJETO to [dashboard] 
go

grant select on VIEW_ATENDIMENTO_TECNICO to [dashboard] 
go

grant select on VIEW_MTBF_MES_A_MES to [dashboard] 
go

grant select on VIEW_MTTR_MES_A_MES to [dashboard] 
go